FROM node:9

RUN apt-get update && apt-get install apt-transport-https

RUN yarn global add \
      doctoc \
      elm@0.18 \
      heroku \
      http-server \
      jsdoc \
      json-server \
      js-yaml \
      livedown \
      prettier \
      standard

USER node
